-- Disable RLS for hackathon (enable in production!)
-- Run this in Supabase SQL Editor

-- Core tables
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_certifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_training DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_availability DISABLE ROW LEVEL SECURITY;

-- Job tables
ALTER TABLE IF EXISTS jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_status_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_dispatch_attempts DISABLE ROW LEVEL SECURITY;

-- Payment tables
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS worker_wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payout_requests DISABLE ROW LEVEL SECURITY;

-- Notification tables
ALTER TABLE IF EXISTS notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_tokens DISABLE ROW LEVEL SECURITY;

-- Service tables
ALTER TABLE IF EXISTS service_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_subcategories DISABLE ROW LEVEL SECURITY;

-- Analytics tables
ALTER TABLE IF EXISTS demand_forecasts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS skill_gap_analyses DISABLE ROW LEVEL SECURITY;

-- Other tables
ALTER TABLE IF EXISTS otp_verifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_audit_log DISABLE ROW LEVEL SECURITY;
